config/routes.rb
Rails.application.routes.draw do
  # , :controllers => { :registrations => "user/registrations" } is saying is the registrations path look through the controllers
  # look that the user/registrations first the subclasses from devise
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :user_stocks, except: [:show, :edit, :update]
  resources :users, only: [:show]
  resources :friendships
  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stocks', to: 'stocks#search'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'

end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#            user_password PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
#                          POST   /users/password(.:format)      devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#        user_registration PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
#                          POST   /users(.:format)               devise/registrations#create

app/views/friends/_lookup.html.erb
<div id="friend-lookup">
  <h3>Search for friends</h3>
  <!-- remote: true, method: :get is saying that this is a AJAX look up, we are going to use the id for jquery -->
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <!-- text_field_tag :friend, params[:friend] is how you assign what you want to search for -->
        <%= text_field_tag :search_param, params[:search_param], placeholder: "first name, last name, or email", autofocus: true, class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Look Up a Person
        <% end %>
      </div>
    </div>
  <% end %>
  <%= render 'common/spinner' %>
  <% if @users %>
    <% if @users.size > 0 %>
      <div id="friend-lookup-results" class="well results-block col-md-10">
        <table class="search-results-results col-md-12">
          <tbody>
            <% @users.each do |user|%>
            <tr>
              <td><strong>Name: </strong> <%= user.full_name %></td>
              <td><strong>Email: </strong> <%= user.email %></td>
              <td>
                <strong>Profile: </strong> <%= link_to "View Profile", user_path(user), class: "btn btn-xs btn-success" %>
                <% if current_user.not_friends_with?(user.id) %>
                <%= link_to "Add Friend", add_friend_path(user: current_user, friend: user), class:  "btn btn-xs btn-success", method: :post %>
                <% else %>
                <span class="label label-primary">You Are friends</span>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p class="col-md-12">No people match this search.</p>
    <% end %>
  <% end %>
  <div id="friend-lookup-errors"></div>
</div>