config/routes.rb
Rails.application.routes.draw do
  # , :controllers => { :registrations => "user/registrations" } is saying is the registrations path look through the controllers
  # look that the user/registrations first the subclasses from devise
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :user_stocks, except: [:show, :edit, :update]
  resources :users, only: [:show]
  resources :friendships
  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stocks', to: 'stocks#search'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'

end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#            user_password PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
#                          POST   /users/password(.:format)      devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#        user_registration PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
#                          POST   /users(.:format)               devise/registrations#create

app/models/stock.rb
class Stock < ApplicationRecord

  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def self.new_from_lookup(ticker_symbol)

    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    return nil unless looked_up_stock.name

    new_stock = new(ticker:looked_up_stock.symbol, name: looked_up_stock.name)
    new_stock.last_price = new_stock.price
    new_stock
  end

  def price

    closing_price = StockQuote::Stock.quote(ticker).close
    opening_price = StockQuote::Stock.quote(ticker).open
    if closing_price
      return "#{closing_price} (Closing)"
    elsif opening_price
      return "#{opening_price} (Opening)"
    else
      return 'Unavailable'
  end
end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock])
      @stock ||= Stock.new_from_lookup(params[:stock])
    end

    if @stock
      # a good way to see if the methods are working is to render the jason version
      # http://localhost:3000/search_stocks?stock=GOOG could be a way to replace console.log
      # render json: @stock
       render partial: 'lookup'
    else
      render status: :not_found, nothing: true
    end
  end
end

app/views/stocks/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock|%>
    <tr>
      <td><%= user_stock.name %></td>
      <td><%= user_stock.ticker %></td>
      <td><%= user_stock.price %></td>
      <% if @user.id == current_user.id%>
      <td><%= link_to "Delete", user_stock_path(user_stock), :method => :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/_lookup.html.erb
<div id="stock-lookup">
  <h3>Search for Stocks</h3>
  <!-- remote: true, method: :get is saying that this is a AJAX look up, we are going to use the id for jquery -->
  <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <!-- text_field_tag :stock, params[:stock] is how you assign what you want to search for -->
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock Ticker Symbol", autofocus: true, class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Look up a stock
        <% end %>
      </div>
    </div>
  <% end %>
  <%= render 'common/spinner' %>
  <% if @stock %>
    <div id="stock-lookup-results" class="well results-block">
      <strong>Symbol: </strong> <%= @stock.ticker %>
      <strong>Name: </strong> <%= @stock.name %>
      <strong>Price: </strong> <%= @stock.price %>
      <% if current_user.can_add_stock?(@stock.ticker) %>
        <%= link_to "Add to my Stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker,
        stock_id: @stock.id ? @stock.id : "" ), class: "btn btn-xs btn-success", method: :post %>
      <% else %>
      <span class='label label-default'>
        <span class="label label-defualt ">
          Stock can not be added becuase you already added
          <% if !current_user.under_stock_limit? %>
            10 stocks.
          <% end %>
          <% if current_user.stock_already_added?(@stock.ticker) %>
            this stock.
          <% end %>
        </span>
      <% end %>
    </div>
  <% end %>
    <div id="stock-lookup-errors"></div>
</div>